{
 "title": "Laptop Metric",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage Percentage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 16, "x": 0, "y": 0 },
   "targets": [
    { "expr": "laptop_cpu_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "laptop_memory_used_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Jvm Thread Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_thread_count", "legendFormat": "__auto" }
   ]
  }
 ]
}